[OK]"[OK]"[OK]"[OK][OK]
[OK]C[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK] [OK]P[OK]o[OK]s[OK]t[OK]g[OK]r[OK]e[OK]S[OK]Q[OK]L[OK] [OK]s[OK]e[OK]e[OK]d[OK] [OK]s[OK]c[OK]r[OK]i[OK]p[OK]t[OK] [OK]f[OK]o[OK]r[OK] [OK]a[OK]l[OK]l[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK][OK]
[OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]s[OK] [OK]r[OK]e[OK]a[OK]l[OK]i[OK]s[OK]t[OK]i[OK]c[OK],[OK] [OK]c[OK]o[OK]n[OK]s[OK]i[OK]s[OK]t[OK]e[OK]n[OK]t[OK] [OK]d[OK]a[OK]t[OK]a[OK] [OK]f[OK]o[OK]r[OK] [OK]l[OK]o[OK]a[OK]d[OK] [OK]t[OK]e[OK]s[OK]t[OK]i[OK]n[OK]g[OK][OK]
[OK]"[OK]"[OK]"[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]p[OK]s[OK]y[OK]c[OK]o[OK]p[OK]g[OK]2[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK],[OK] [OK]t[OK]i[OK]m[OK]e[OK]d[OK]e[OK]l[OK]t[OK]a[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]u[OK]u[OK]i[OK]d[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]u[OK]u[OK]i[OK]d[OK]4[OK][OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]t[OK]i[OK]m[OK]e[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]i[OK]m[OK]e[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]_[OK]t[OK]o[OK]k[OK]e[OK]n[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]x[OK]p[OK]i[OK]r[OK]e[OK]_[OK]t[OK]i[OK]m[OK]e[OK] [OK]=[OK] [OK]i[OK]n[OK]t[OK]([OK]t[OK]i[OK]m[OK]e[OK]([OK])[OK])[OK] [OK]+[OK] [OK]3[OK]0[OK] [OK]*[OK] [OK]2[OK]4[OK] [OK]*[OK] [OK]6[OK]0[OK] [OK]*[OK] [OK]6[OK]0[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]f[OK]"[OK]{[OK]e[OK]x[OK]p[OK]i[OK]r[OK]e[OK]_[OK]t[OK]i[OK]m[OK]e[OK]}[OK]_[OK]{[OK]u[OK]u[OK]i[OK]d[OK]4[OK]([OK])[OK]}[OK]"[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]_[OK]m[OK]e[OK]m[OK]o[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK] [OK]'[OK]'[OK].[OK]j[OK]o[OK]i[OK]n[OK]([OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]s[OK]([OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK].[OK]a[OK]s[OK]c[OK]i[OK]i[OK]_[OK]u[OK]p[OK]p[OK]e[OK]r[OK]c[OK]a[OK]s[OK]e[OK] [OK]+[OK] [OK]s[OK]t[OK]r[OK]i[OK]n[OK]g[OK].[OK]d[OK]i[OK]g[OK]i[OK]t[OK]s[OK],[OK] [OK]k[OK]=[OK]8[OK])[OK])[OK][OK]
[OK][OK]
[OK]d[OK]e[OK]f[OK] [OK]s[OK]e[OK]e[OK]d[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]_[OK]d[OK]a[OK]t[OK]a[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK] [OK]=[OK] [OK]p[OK]s[OK]y[OK]c[OK]o[OK]p[OK]g[OK]2[OK].[OK]c[OK]o[OK]n[OK]n[OK]e[OK]c[OK]t[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]h[OK]o[OK]s[OK]t[OK]=[OK]'[OK]1[OK]2[OK]7[OK].[OK]0[OK].[OK]0[OK].[OK]1[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]o[OK]r[OK]t[OK]=[OK]5[OK]4[OK]3[OK]3[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]u[OK]s[OK]e[OK]r[OK]=[OK]'[OK]l[OK]o[OK]a[OK]d[OK]t[OK]e[OK]s[OK]t[OK]_[OK]u[OK]s[OK]e[OK]r[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]a[OK]s[OK]s[OK]w[OK]o[OK]r[OK]d[OK]=[OK]'[OK]L[OK]o[OK]a[OK]d[OK]T[OK]e[OK]s[OK]t[OK]2[OK]0[OK]2[OK]4[OK]![OK]S[OK]e[OK]c[OK]u[OK]r[OK]e[OK]P[OK]a[OK]s[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]a[OK]b[OK]a[OK]s[OK]e[OK]=[OK]'[OK]l[OK]o[OK]a[OK]d[OK]t[OK]e[OK]s[OK]t[OK]_[OK]d[OK]b[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK] [OK]=[OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]C[OK]O[OK]M[OK]P[OK]L[OK]E[OK]T[OK]E[OK] [OK]P[OK]O[OK]S[OK]T[OK]G[OK]R[OK]E[OK]S[OK]Q[OK]L[OK] [OK]D[OK]A[OK]T[OK]A[OK] [OK]S[OK]E[OK]E[OK]D[OK]I[OK]N[OK]G[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]C[OK]l[OK]e[OK]a[OK]r[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]d[OK]a[OK]t[OK]a[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK].[OK] [OK]C[OK]l[OK]e[OK]a[OK]r[OK]i[OK]n[OK]g[OK] [OK]e[OK]x[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK] [OK]d[OK]a[OK]t[OK]a[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]d[OK]e[OK]a[OK]l[OK]_[OK]g[OK]i[OK]v[OK]e[OK]d[OK]_[OK]g[OK]i[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]d[OK]e[OK]a[OK]l[OK]_[OK]s[OK]e[OK]n[OK]d[OK]e[OK]d[OK]_[OK]g[OK]i[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]_[OK]n[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]n[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]r[OK]e[OK]q[OK]u[OK]i[OK]r[OK]e[OK]m[OK]e[OK]n[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]r[OK]a[OK]d[OK]e[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]b[OK]i[OK]d[OK]s[OK]'[OK],[OK] [OK]'[OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK]'[OK],[OK] [OK]'[OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]n[OK]f[OK]t[OK]_[OK]o[OK]r[OK]d[OK]e[OK]r[OK]s[OK]'[OK],[OK] [OK]'[OK]n[OK]f[OK]t[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK]'[OK],[OK] [OK]'[OK]n[OK]f[OK]t[OK]_[OK]p[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]c[OK]h[OK]a[OK]n[OK]n[OK]e[OK]l[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK]'[OK],[OK] [OK]'[OK]c[OK]h[OK]a[OK]n[OK]n[OK]e[OK]l[OK]s[OK]_[OK]g[OK]i[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]c[OK]h[OK]a[OK]n[OK]n[OK]e[OK]l[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]d[OK]e[OK]a[OK]l[OK]s[OK]_[OK]g[OK]i[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]_[OK]n[OK]f[OK]t[OK]_[OK]f[OK]l[OK]o[OK]o[OK]r[OK]s[OK]'[OK],[OK] [OK]'[OK]n[OK]f[OK]t[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK]_[OK]t[OK]o[OK]p[OK]u[OK]p[OK]s[OK]'[OK],[OK] [OK]'[OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK]_[OK]w[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK]'[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]'[OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]g[OK]i[OK]f[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK]'[OK],[OK] [OK]'[OK]u[OK]s[OK]e[OK]r[OK]s[OK]'[OK][OK]
[OK] [OK] [OK] [OK] [OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK] [OK]i[OK]n[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK]f[OK]"[OK]T[OK]R[OK]U[OK]N[OK]C[OK]A[OK]T[OK]E[OK] [OK]T[OK]A[OK]B[OK]L[OK]E[OK] [OK]{[OK]t[OK]a[OK]b[OK]l[OK]e[OK]}[OK] [OK]C[OK]A[OK]S[OK]C[OK]A[OK]D[OK]E[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK][[OK]O[OK]K[OK]][OK] [OK]C[OK]l[OK]e[OK]a[OK]r[OK]e[OK]d[OK] [OK]a[OK]l[OK]l[OK] [OK]t[OK]a[OK]b[OK]l[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK].[OK] [OK]U[OK]s[OK]e[OK]r[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]2[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]1[OK],[OK]0[OK]0[OK]0[OK] [OK]u[OK]s[OK]e[OK]r[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK] [OK]+[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]u[OK]s[OK]e[OK]r[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]t[OK]o[OK]k[OK]e[OK]n[OK],[OK] [OK]l[OK]a[OK]n[OK]g[OK]u[OK]a[OK]g[OK]e[OK],[OK] [OK]m[OK]e[OK]m[OK]o[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]_[OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK],[OK] [OK]"[OK]g[OK]r[OK]o[OK]u[OK]p[OK]"[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]'[OK]m[OK]e[OK]m[OK]b[OK]e[OK]r[OK]'[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]_[OK]t[OK]o[OK]k[OK]e[OK]n[OK]([OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]e[OK]n[OK]'[OK],[OK] [OK]'[OK]r[OK]u[OK]'[OK],[OK] [OK]'[OK]e[OK]s[OK]'[OK]][OK])[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]g[OK]e[OK]n[OK]e[OK]r[OK]a[OK]t[OK]e[OK]_[OK]m[OK]e[OK]m[OK]o[OK]([OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK]}[OK] [OK]u[OK]s[OK]e[OK]r[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]2[OK].[OK] [OK]M[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]3[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]"[OK]m[OK]r[OK]k[OK]t[OK]"[OK],[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]s[OK]:[OK]/[OK]/[OK]c[OK]d[OK]n[OK].[OK]t[OK]g[OK]m[OK]r[OK]k[OK]t[OK].[OK]i[OK]o[OK]/[OK]i[OK]c[OK]o[OK]n[OK]s[OK]/[OK]c[OK]o[OK]m[OK]m[OK]o[OK]n[OK]/[OK]l[OK]o[OK]g[OK]o[OK].[OK]s[OK]v[OK]g[OK]"[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]"[OK]p[OK]o[OK]r[OK]t[OK]a[OK]l[OK]s[OK]"[OK],[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]s[OK]:[OK]/[OK]/[OK]a[OK]p[OK]i[OK].[OK]s[OK]o[OK]l[OK]d[OK]o[OK]u[OK]t[OK].[OK]t[OK]o[OK]p[OK]/[OK]m[OK]e[OK]d[OK]i[OK]a[OK]/[OK]p[OK]o[OK]r[OK]t[OK]a[OK]l[OK]s[OK]_[OK]l[OK]o[OK]g[OK]o[OK].[OK]j[OK]p[OK]g[OK]"[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]"[OK]t[OK]o[OK]n[OK]n[OK]e[OK]l[OK]"[OK],[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]s[OK]:[OK]/[OK]/[OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]p[OK]l[OK]a[OK]c[OK]e[OK].[OK]t[OK]o[OK]n[OK]n[OK]e[OK]l[OK].[OK]n[OK]e[OK]t[OK]w[OK]o[OK]r[OK]k[OK]/[OK]i[OK]c[OK]o[OK]n[OK].[OK]s[OK]v[OK]g[OK]"[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]t[OK]i[OK]t[OK]l[OK]e[OK],[OK] [OK]l[OK]o[OK]g[OK]o[OK] [OK]i[OK]n[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK] [OK]([OK]t[OK]i[OK]t[OK]l[OK]e[OK],[OK] [OK]l[OK]o[OK]g[OK]o[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]t[OK]i[OK]t[OK]l[OK]e[OK],[OK] [OK]l[OK]o[OK]g[OK]o[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK])[OK]}[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]3[OK].[OK] [OK]G[OK]i[OK]f[OK]t[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]4[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]2[OK]0[OK]0[OK] [OK]g[OK]i[OK]f[OK]t[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK] [OK]=[OK] [OK][[OK]"[OK]D[OK]e[OK]l[OK]i[OK]c[OK]i[OK]o[OK]u[OK]s[OK] [OK]C[OK]a[OK]k[OK]e[OK]"[OK],[OK] [OK]"[OK]B[OK]l[OK]u[OK]e[OK] [OK]S[OK]t[OK]a[OK]r[OK]"[OK],[OK] [OK]"[OK]R[OK]e[OK]d[OK] [OK]H[OK]e[OK]a[OK]r[OK]t[OK]"[OK],[OK] [OK]"[OK]G[OK]r[OK]e[OK]e[OK]n[OK] [OK]C[OK]l[OK]o[OK]v[OK]e[OK]r[OK]"[OK],[OK] [OK]"[OK]G[OK]o[OK]l[OK]d[OK]e[OK]n[OK] [OK]C[OK]r[OK]o[OK]w[OK]n[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]P[OK]u[OK]r[OK]p[OK]l[OK]e[OK] [OK]D[OK]i[OK]a[OK]m[OK]o[OK]n[OK]d[OK]"[OK],[OK] [OK]"[OK]O[OK]r[OK]a[OK]n[OK]g[OK]e[OK] [OK]B[OK]a[OK]l[OK]l[OK]o[OK]o[OK]n[OK]"[OK],[OK] [OK]"[OK]P[OK]i[OK]n[OK]k[OK] [OK]R[OK]o[OK]s[OK]e[OK]"[OK],[OK] [OK]"[OK]S[OK]i[OK]l[OK]v[OK]e[OK]r[OK] [OK]M[OK]e[OK]d[OK]a[OK]l[OK]"[OK],[OK] [OK]"[OK]B[OK]r[OK]o[OK]n[OK]z[OK]e[OK] [OK]T[OK]r[OK]o[OK]p[OK]h[OK]y[OK]"[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]2[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]g[OK]i[OK]f[OK]t[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]t[OK]i[OK]t[OK]l[OK]e[OK],[OK] [OK]n[OK]u[OK]m[OK],[OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]_[OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]_[OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]b[OK]a[OK]c[OK]k[OK]d[OK]r[OK]o[OK]p[OK]_[OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]m[OK]o[OK]d[OK]e[OK]l[OK]_[OK]r[OK]a[OK]r[OK]i[OK]t[OK]y[OK],[OK] [OK]p[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK]_[OK]r[OK]a[OK]r[OK]i[OK]t[OK]y[OK],[OK] [OK]b[OK]a[OK]c[OK]k[OK]d[OK]r[OK]o[OK]p[OK]_[OK]r[OK]a[OK]r[OK]i[OK]t[OK]y[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]v[OK]a[OK]i[OK]l[OK]a[OK]b[OK]i[OK]l[OK]i[OK]t[OK]y[OK]_[OK]t[OK]o[OK]t[OK]a[OK]l[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]f[OK]"[OK]{[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]n[OK]a[OK]m[OK]e[OK]s[OK])[OK]}[OK] [OK]#[OK]{[OK]i[OK]}[OK]"[OK],[OK] [OK]i[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]"[OK]M[OK]o[OK]d[OK]e[OK]l[OK] [OK]{[OK]i[OK] [OK]%[OK] [OK]2[OK]0[OK]}[OK]"[OK],[OK] [OK]f[OK]"[OK]P[OK]a[OK]t[OK]t[OK]e[OK]r[OK]n[OK] [OK]{[OK]i[OK] [OK]%[OK] [OK]1[OK]0[OK]}[OK]"[OK],[OK] [OK]f[OK]"[OK]B[OK]a[OK]c[OK]k[OK]d[OK]r[OK]o[OK]p[OK] [OK]{[OK]i[OK] [OK]%[OK] [OK]5[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]u[OK]n[OK]i[OK]f[OK]o[OK]r[OK]m[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]u[OK]n[OK]i[OK]f[OK]o[OK]r[OK]m[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]u[OK]n[OK]i[OK]f[OK]o[OK]r[OK]m[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK]0[OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK]}[OK] [OK]g[OK]i[OK]f[OK]t[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]4[OK].[OK] [OK]A[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]5[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]2[OK]0[OK]0[OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]2[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]f[OK]"[OK]t[OK]e[OK]s[OK]t[OK]_[OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]{[OK]i[OK]}[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]i[OK]s[OK]_[OK]a[OK]c[OK]t[OK]i[OK]v[OK]e[OK],[OK] [OK]p[OK]h[OK]o[OK]n[OK]e[OK],[OK] [OK]n[OK]a[OK]m[OK]e[OK],[OK] [OK]t[OK]e[OK]l[OK]e[OK]g[OK]r[OK]a[OK]m[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]t[OK]a[OK]r[OK]s[OK]_[OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]s[OK]_[OK]p[OK]r[OK]e[OK]m[OK]i[OK]u[OK]m[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]t[OK]r[OK]u[OK]e[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]f[OK]"[OK]+[OK]1[OK]2[OK]3[OK]4[OK]5[OK]6[OK]7[OK]{[OK]i[OK]:[OK]0[OK]5[OK]d[OK]}[OK]"[OK],[OK] [OK]f[OK]"[OK]T[OK]e[OK]s[OK]t[OK] [OK]A[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK] [OK]{[OK]i[OK]}[OK]"[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]2[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK] [OK]+[OK] [OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]0[OK],[OK] [OK]1[OK]0[OK]0[OK]0[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]T[OK]r[OK]u[OK]e[OK],[OK] [OK]F[OK]a[OK]l[OK]s[OK]e[OK]][OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK]}[OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]5[OK].[OK] [OK]N[OK]F[OK]T[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]6[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]1[OK],[OK]0[OK]0[OK]0[OK] [OK]N[OK]F[OK]T[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]n[OK]f[OK]t[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]m[OK]s[OK]g[OK]_[OK]i[OK]d[OK],[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]a[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK] [OK]i[OK]f[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK]([OK])[OK] [OK]>[OK] [OK]0[OK].[OK]3[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]N[OK]o[OK]n[OK]e[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]4[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK] [OK]+[OK] [OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK] [OK]i[OK]f[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK]([OK])[OK] [OK]>[OK] [OK]0[OK].[OK]3[OK] [OK]e[OK]l[OK]s[OK]e[OK] [OK]N[OK]o[OK]n[OK]e[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]{[OK]l[OK]e[OK]n[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK]}[OK] [OK]N[OK]F[OK]T[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]6[OK].[OK] [OK]N[OK]F[OK]T[OK] [OK]O[OK]r[OK]d[OK]e[OK]r[OK]s[OK] [OK]([OK]o[OK]f[OK]f[OK]e[OK]r[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]7[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]2[OK]0[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]o[OK]r[OK]d[OK]e[OK]r[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]2[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]n[OK]f[OK]t[OK]_[OK]o[OK]r[OK]d[OK]e[OK]r[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]2[OK]0[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]o[OK]r[OK]d[OK]e[OK]r[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]7[OK].[OK] [OK]N[OK]F[OK]T[OK] [OK]D[OK]e[OK]a[OK]l[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]8[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]3[OK]0[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]d[OK]e[OK]a[OK]l[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]3[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]n[OK]f[OK]t[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]e[OK]l[OK]l[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]b[OK]u[OK]y[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]3[OK]0[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]d[OK]e[OK]a[OK]l[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]8[OK].[OK] [OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]9[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]1[OK]0[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]t[OK]a[OK]r[OK]t[OK]_[OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]t[OK]_[OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]n[OK]d[OK]_[OK]t[OK]i[OK]m[OK]e[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]5[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK].[OK]n[OK]o[OK]w[OK]([OK])[OK] [OK]+[OK] [OK]t[OK]i[OK]m[OK]e[OK]d[OK]e[OK]l[OK]t[OK]a[OK]([OK]d[OK]a[OK]y[OK]s[OK]=[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]7[OK])[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]a[OK]c[OK]t[OK]i[OK]v[OK]e[OK]'[OK],[OK] [OK]'[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]d[OK]'[OK],[OK] [OK]'[OK]c[OK]a[OK]n[OK]c[OK]e[OK]l[OK]l[OK]e[OK]d[OK]'[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]1[OK]0[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]9[OK].[OK] [OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]B[OK]i[OK]d[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]0[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]3[OK]0[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]b[OK]i[OK]d[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]3[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]b[OK]i[OK]d[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]a[OK]m[OK]o[OK]u[OK]n[OK]t[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]3[OK]0[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]b[OK]i[OK]d[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]0[OK].[OK] [OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]D[OK]e[OK]a[OK]l[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]1[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]5[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]d[OK]e[OK]a[OK]l[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]5[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]d[OK]e[OK]a[OK]l[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK],[OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]e[OK]l[OK]l[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]b[OK]u[OK]y[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]5[OK]0[OK] [OK]a[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]d[OK]e[OK]a[OK]l[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]1[OK].[OK] [OK]T[OK]r[OK]a[OK]d[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]2[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]1[OK]0[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]a[OK]c[OK]t[OK]i[OK]v[OK]e[OK]'[OK],[OK] [OK]'[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]d[OK]'[OK],[OK] [OK]'[OK]c[OK]a[OK]n[OK]c[OK]e[OK]l[OK]l[OK]e[OK]d[OK]'[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]1[OK]0[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]2[OK].[OK] [OK]T[OK]r[OK]a[OK]d[OK]e[OK] [OK]N[OK]F[OK]T[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]3[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]2[OK]0[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK] [OK]N[OK]F[OK]T[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]2[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]n[OK]f[OK]t[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK],[OK] [OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]n[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]2[OK]0[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK] [OK]N[OK]F[OK]T[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]3[OK].[OK] [OK]T[OK]r[OK]a[OK]d[OK]e[OK] [OK]A[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]4[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]1[OK]5[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK] [OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]p[OK]p[OK]_[OK]i[OK]d[OK]s[OK] [OK]=[OK] [OK][[OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]1[OK]5[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]p[OK]p[OK]_[OK]i[OK]d[OK] [OK]=[OK] [OK]i[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]p[OK]p[OK]_[OK]i[OK]d[OK]s[OK].[OK]a[OK]p[OK]p[OK]e[OK]n[OK]d[OK]([OK]a[OK]p[OK]p[OK]_[OK]i[OK]d[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]a[OK]p[OK]p[OK]_[OK]i[OK]d[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]t[OK]r[OK]a[OK]d[OK]e[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]p[OK]e[OK]n[OK]d[OK]i[OK]n[OK]g[OK]'[OK],[OK] [OK]'[OK]a[OK]c[OK]c[OK]e[OK]p[OK]t[OK]e[OK]d[OK]'[OK],[OK] [OK]'[OK]r[OK]e[OK]j[OK]e[OK]c[OK]t[OK]e[OK]d[OK]'[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]1[OK]5[OK]0[OK] [OK]t[OK]r[OK]a[OK]d[OK]e[OK] [OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]4[OK].[OK] [OK]N[OK]F[OK]T[OK] [OK]P[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]5[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]5[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]p[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]5[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]n[OK]f[OK]t[OK]_[OK]p[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]5[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]a[OK]c[OK]t[OK]i[OK]v[OK]e[OK]'[OK],[OK] [OK]'[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]d[OK]'[OK],[OK] [OK]'[OK]c[OK]a[OK]n[OK]c[OK]e[OK]l[OK]l[OK]e[OK]d[OK]'[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]5[OK]0[OK] [OK]N[OK]F[OK]T[OK] [OK]p[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]5[OK].[OK] [OK]B[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]T[OK]o[OK]p[OK]u[OK]p[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]6[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]5[OK]0[OK]0[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]t[OK]o[OK]p[OK]u[OK]p[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]5[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK]_[OK]t[OK]o[OK]p[OK]u[OK]p[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]a[OK]m[OK]o[OK]u[OK]n[OK]t[OK],[OK] [OK]t[OK]i[OK]m[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]1[OK]0[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]t[OK]r[OK]([OK]i[OK]n[OK]t[OK]([OK]([OK]d[OK]a[OK]t[OK]e[OK]t[OK]i[OK]m[OK]e[OK].[OK]n[OK]o[OK]w[OK]([OK])[OK] [OK]-[OK] [OK]t[OK]i[OK]m[OK]e[OK]d[OK]e[OK]l[OK]t[OK]a[OK]([OK]d[OK]a[OK]y[OK]s[OK]=[OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]0[OK],[OK] [OK]3[OK]0[OK])[OK])[OK])[OK].[OK]t[OK]i[OK]m[OK]e[OK]s[OK]t[OK]a[OK]m[OK]p[OK]([OK])[OK])[OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]5[OK]0[OK]0[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]t[OK]o[OK]p[OK]u[OK]p[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]6[OK].[OK] [OK]B[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]W[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]7[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]2[OK]0[OK]0[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]w[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]i[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]g[OK]e[OK]([OK]1[OK],[OK] [OK]2[OK]0[OK]1[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK]_[OK]w[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK] [OK]([OK]i[OK]d[OK],[OK] [OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK],[OK] [OK]a[OK]m[OK]o[OK]u[OK]n[OK]t[OK],[OK] [OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]i[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK]u[OK]s[OK]e[OK]r[OK]_[OK]i[OK]d[OK]s[OK])[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]5[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]p[OK]e[OK]n[OK]d[OK]i[OK]n[OK]g[OK]'[OK],[OK] [OK]'[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]d[OK]'[OK],[OK] [OK]'[OK]r[OK]e[OK]j[OK]e[OK]c[OK]t[OK]e[OK]d[OK]'[OK]][OK])[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]2[OK]0[OK]0[OK] [OK]b[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]w[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]1[OK]7[OK].[OK] [OK]M[OK]a[OK]r[OK]k[OK]e[OK]t[OK] [OK]N[OK]F[OK]T[OK] [OK]F[OK]l[OK]o[OK]o[OK]r[OK]s[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]1[OK]8[OK].[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]i[OK]n[OK]g[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK] [OK]f[OK]l[OK]o[OK]o[OK]r[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK]s[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK] [OK]i[OK]n[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]s[OK]a[OK]m[OK]p[OK]l[OK]e[OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK]s[OK],[OK] [OK]5[OK]0[OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]e[OK]x[OK]e[OK]c[OK]u[OK]t[OK]e[OK]([OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]N[OK]S[OK]E[OK]R[OK]T[OK] [OK]I[OK]N[OK]T[OK]O[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK]_[OK]n[OK]f[OK]t[OK]_[OK]f[OK]l[OK]o[OK]o[OK]r[OK]s[OK] [OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK],[OK] [OK]f[OK]l[OK]o[OK]o[OK]r[OK]_[OK]p[OK]r[OK]i[OK]c[OK]e[OK],[OK] [OK]c[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK]_[OK]a[OK]t[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]V[OK]A[OK]L[OK]U[OK]E[OK]S[OK] [OK]([OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]%[OK]s[OK],[OK] [OK]N[OK]O[OK]W[OK]([OK])[OK])[OK]"[OK]"[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]([OK]g[OK]i[OK]f[OK]t[OK]_[OK]i[OK]d[OK],[OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]c[OK]h[OK]o[OK]i[OK]c[OK]e[OK]([OK][[OK]'[OK]m[OK]r[OK]k[OK]t[OK]'[OK],[OK] [OK]'[OK]p[OK]o[OK]r[OK]t[OK]a[OK]l[OK]s[OK]'[OK],[OK] [OK]'[OK]t[OK]o[OK]n[OK]n[OK]e[OK]l[OK]'[OK]][OK])[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]a[OK]n[OK]d[OK]o[OK]m[OK].[OK]r[OK]a[OK]n[OK]d[OK]i[OK]n[OK]t[OK]([OK]1[OK],[OK] [OK]5[OK]0[OK])[OK] [OK]*[OK] [OK]1[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]o[OK]m[OK]m[OK]i[OK]t[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]â[OK]œ[OK]“[OK] [OK]C[OK]r[OK]e[OK]a[OK]t[OK]e[OK]d[OK] [OK]5[OK]0[OK] [OK]m[OK]a[OK]r[OK]k[OK]e[OK]t[OK] [OK]f[OK]l[OK]o[OK]o[OK]r[OK] [OK]p[OK]r[OK]i[OK]c[OK]e[OK]s[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]u[OK]r[OK]s[OK]o[OK]r[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]c[OK]o[OK]n[OK]n[OK].[OK]c[OK]l[OK]o[OK]s[OK]e[OK]([OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]\[OK]n[OK]"[OK] [OK]+[OK] [OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]P[OK]O[OK]S[OK]T[OK]G[OK]R[OK]E[OK]S[OK]Q[OK]L[OK] [OK]S[OK]E[OK]E[OK]D[OK]I[OK]N[OK]G[OK] [OK]C[OK]O[OK]M[OK]P[OK]L[OK]E[OK]T[OK]E[OK]D[OK] [OK]S[OK]U[OK]C[OK]C[OK]E[OK]S[OK]S[OK]F[OK]U[OK]L[OK]L[OK]Y[OK]![OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]U[OK]s[OK]e[OK]r[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]1[OK],[OK]0[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]M[OK]a[OK]r[OK]k[OK]e[OK]t[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]3[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]G[OK]i[OK]f[OK]t[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]2[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]A[OK]c[OK]c[OK]o[OK]u[OK]n[OK]t[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]2[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]N[OK]F[OK]T[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]1[OK],[OK]0[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]N[OK]F[OK]T[OK] [OK]O[OK]r[OK]d[OK]e[OK]r[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]2[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]N[OK]F[OK]T[OK] [OK]D[OK]e[OK]a[OK]l[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]3[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]1[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]B[OK]i[OK]d[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]3[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]A[OK]u[OK]c[OK]t[OK]i[OK]o[OK]n[OK] [OK]D[OK]e[OK]a[OK]l[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK]5[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]T[OK]r[OK]a[OK]d[OK]e[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]1[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]T[OK]r[OK]a[OK]d[OK]e[OK] [OK]N[OK]F[OK]T[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]2[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]T[OK]r[OK]a[OK]d[OK]e[OK] [OK]A[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]s[OK]:[OK] [OK]1[OK]5[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]N[OK]F[OK]T[OK] [OK]P[OK]r[OK]e[OK]s[OK]a[OK]l[OK]e[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]5[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]B[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]T[OK]o[OK]p[OK]u[OK]p[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK]5[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]B[OK]a[OK]l[OK]a[OK]n[OK]c[OK]e[OK] [OK]W[OK]i[OK]t[OK]h[OK]d[OK]r[OK]a[OK]w[OK]s[OK]:[OK] [OK] [OK]2[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]M[OK]a[OK]r[OK]k[OK]e[OK]t[OK] [OK]F[OK]l[OK]o[OK]o[OK]r[OK]s[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK]5[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]T[OK]O[OK]T[OK]A[OK]L[OK] [OK]R[OK]E[OK]C[OK]O[OK]R[OK]D[OK]S[OK]:[OK] [OK] [OK] [OK] [OK] [OK] [OK]~[OK]4[OK],[OK]5[OK]0[OK]0[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]"[OK]=[OK]"[OK]*[OK]6[OK]0[OK])[OK][OK]
[OK][OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]"[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]"[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]s[OK]e[OK]e[OK]d[OK]_[OK]c[OK]o[OK]m[OK]p[OK]l[OK]e[OK]t[OK]e[OK]_[OK]d[OK]a[OK]t[OK]a[OK]([OK])[OK][OK]
[OK]
