"""add_stars_purchases_table

Revision ID: 20241216_add_stars_purchases
Revises: 20241211_add_frozen_balance
Create Date: 2024-12-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime, func

# revision identifiers, used by Alembic.
revision = '20241216_add_stars_purchases'
down_revision = '20241211_frozen'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars_purchases',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('recipient_username', sa.String(length=255), nullable=False),
        sa.Column('stars_amount', sa.Integer(), nullable=False),
        sa.Column('price_nanotons', sa.BigInteger(), nullable=False, comment='Цена в nanotons'),
        sa.Column('fragment_cost_ton', sa.Float(), nullable=True, comment='Реальная стоимость Fragment'),
        sa.Column('fragment_tx_id', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('error_message', sa.String(length=500), nullable=True),
        sa.Column('created_at', DateTime, server_default=func.now()),
        sa.Column('updated_at', DateTime, server_default=func.now(), onupdate=func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stars_purchases_user_created', 'stars_purchases', ['user_id', 'created_at'])
    op.create_index('ix_stars_purchases_status', 'stars_purchases', ['status'])
    op.create_index('ix_stars_purchases_recipient', 'stars_purchases', ['recipient_username'])
    op.create_index('ix_stars_purchases_user_id', 'stars_purchases', ['user_id'])
    op.create_index('ix_stars_purchases_fragment_tx_id', 'stars_purchases', ['fragment_tx_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stars_purchases_fragment_tx_id', table_name='stars_purchases')
    op.drop_index('ix_stars_purchases_user_id', table_name='stars_purchases')
    op.drop_index('ix_stars_purchases_recipient', table_name='stars_purchases')
    op.drop_index('ix_stars_purchases_status', table_name='stars_purchases')
    op.drop_index('ix_stars_purchases_user_created', table_name='stars_purchases')
    op.drop_table('stars_purchases')
    # ### end Alembic commands ###