"""initial_schema

Revision ID: ca884ab85b6f
Revises: 
Create Date: 2025-12-06 16:53:34.374865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca884ab85b6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('pattern_name', sa.String(length=255), nullable=True),
    sa.Column('backdrop_name', sa.String(length=255), nullable=True),
    sa.Column('model_rarity', sa.Float(), nullable=True),
    sa.Column('pattern_rarity', sa.Float(), nullable=True),
    sa.Column('backdrop_rarity', sa.Float(), nullable=True),
    sa.Column('center_color', sa.String(length=255), nullable=True),
    sa.Column('edge_color', sa.String(length=255), nullable=True),
    sa.Column('pattern_color', sa.String(length=255), nullable=True),
    sa.Column('text_color', sa.String(length=255), nullable=True),
    sa.Column('availability_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gifts_availability', 'gifts', ['availability_total'], unique=False)
    op.create_index(op.f('ix_gifts_availability_total'), 'gifts', ['availability_total'], unique=False)
    op.create_index(op.f('ix_gifts_num'), 'gifts', ['num'], unique=False)
    op.create_index(op.f('ix_gifts_title'), 'gifts', ['title'], unique=False)
    op.create_index('ix_gifts_title_num', 'gifts', ['title', 'num'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название маркета'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='URL логотипа'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('ix_markets_title', 'markets', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.Boolean(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('memo', sa.String(length=32), nullable=False),
    sa.Column('market_balance', sa.BigInteger(), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_users_group'), 'users', ['group'], unique=False)
    op.create_index('ix_users_group_payment', 'users', ['group', 'payment_status'], unique=False)
    op.create_index(op.f('ix_users_language'), 'users', ['language'], unique=False)
    op.create_index(op.f('ix_users_memo'), 'users', ['memo'], unique=True)
    op.create_index(op.f('ix_users_payment_status'), 'users', ['payment_status'], unique=False)
    op.create_index('ix_users_payment_subscription', 'users', ['payment_status', 'subscription_status'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_code_hash', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('stars_balance', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_active_premium', 'accounts', ['is_active', 'is_premium'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_is_premium'), 'accounts', ['is_premium'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_index(op.f('ix_accounts_phone'), 'accounts', ['phone'], unique=True)
    op.create_index(op.f('ix_accounts_telegram_id'), 'accounts', ['telegram_id'], unique=True)
    op.create_index('ix_accounts_user_active', 'accounts', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('auction_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False, comment='Финальная цена в nanotons'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price > 0', name='check_auction_deal_price_positive'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_deals_buyer_id'), 'auction_deals', ['buyer_id'], unique=False)
    op.create_index('ix_auction_deals_created_at', 'auction_deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_auction_deals_gift_id'), 'auction_deals', ['gift_id'], unique=False)
    op.create_index('ix_auction_deals_gift_price', 'auction_deals', ['gift_id', 'price'], unique=False)
    op.create_index(op.f('ix_auction_deals_price'), 'auction_deals', ['price'], unique=False)
    op.create_index('ix_auction_deals_seller_buyer', 'auction_deals', ['seller_id', 'buyer_id'], unique=False)
    op.create_index(op.f('ix_auction_deals_seller_id'), 'auction_deals', ['seller_id'], unique=False)
    op.create_table('balance_topups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_topups_user_id'), 'balance_topups', ['user_id'], unique=False)
    op.create_table('balance_withdraws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_withdraws_idempotency_key'), 'balance_withdraws', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_balance_withdraws_user_id'), 'balance_withdraws', ['user_id'], unique=False)
    op.create_table('channel_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_nft_floors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя модели или коллекции'),
    sa.Column('price_nanotons', sa.BigInteger(), nullable=False, comment='Цена в nanotons'),
    sa.Column('price_dollars', sa.Float(), nullable=False, comment='Цена в долларах'),
    sa.Column('price_rubles', sa.Float(), nullable=False, comment='Цена в рублях'),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price_dollars >= 0', name='check_market_floor_price_dollars_positive'),
    sa.CheckConstraint('price_nanotons >= 0', name='check_market_floor_price_nanotons_positive'),
    sa.CheckConstraint('price_rubles >= 0', name='check_market_floor_price_rubles_positive'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_nft_floors_created_at', 'market_nft_floors', ['created_at'], unique=False)
    op.create_index('ix_market_nft_floors_market_id', 'market_nft_floors', ['market_id'], unique=False)
    op.create_index('ix_market_nft_floors_name', 'market_nft_floors', ['name'], unique=False)
    op.create_table('nft_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False, comment='Цена в nanotons'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price > 0', name='check_nft_deal_price_positive'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_deals_buyer_id'), 'nft_deals', ['buyer_id'], unique=False)
    op.create_index('ix_nft_deals_created_at', 'nft_deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_nft_deals_gift_id'), 'nft_deals', ['gift_id'], unique=False)
    op.create_index('ix_nft_deals_gift_price', 'nft_deals', ['gift_id', 'price'], unique=False)
    op.create_index(op.f('ix_nft_deals_price'), 'nft_deals', ['price'], unique=False)
    op.create_index('ix_nft_deals_seller_buyer', 'nft_deals', ['seller_id', 'buyer_id'], unique=False)
    op.create_index(op.f('ix_nft_deals_seller_id'), 'nft_deals', ['seller_id'], unique=False)
    op.create_table('nft_presales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True, comment='Цена в nanotons'),
    sa.Column('transfer_time', sa.BigInteger(), nullable=False, comment='Unix timestamp'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price IS NULL OR price > 0', name='check_nft_presale_price_positive'),
    sa.CheckConstraint('transfer_time > 0', name='check_nft_presale_transfer_time_positive'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_presales_buyer_id'), 'nft_presales', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_nft_presales_gift_id'), 'nft_presales', ['gift_id'], unique=False)
    op.create_index(op.f('ix_nft_presales_price'), 'nft_presales', ['price'], unique=False)
    op.create_index(op.f('ix_nft_presales_transfer_time'), 'nft_presales', ['transfer_time'], unique=False)
    op.create_index('ix_nft_presales_user_buyer', 'nft_presales', ['user_id', 'buyer_id'], unique=False)
    op.create_index(op.f('ix_nft_presales_user_id'), 'nft_presales', ['user_id'], unique=False)
    op.create_table('trade_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('reciver_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('gifts_hash', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('msg_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True, comment='Цена в nanotons (NULL = не на продаже)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price IS NULL OR price > 0', name='check_nft_price_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfts_account_id'), 'nfts', ['account_id'], unique=False)
    op.create_index(op.f('ix_nfts_gift_id'), 'nfts', ['gift_id'], unique=False)
    op.create_index('ix_nfts_gift_price', 'nfts', ['gift_id', 'price'], unique=False)
    op.create_index(op.f('ix_nfts_msg_id'), 'nfts', ['msg_id'], unique=False)
    op.create_index(op.f('ix_nfts_price'), 'nfts', ['price'], unique=False)
    op.create_index('ix_nfts_price_not_null', 'nfts', ['price'], unique=False, postgresql_where=sa.text('price IS NOT NULL'))
    op.create_index(op.f('ix_nfts_user_id'), 'nfts', ['user_id'], unique=False)
    op.create_index('ix_nfts_user_price', 'nfts', ['user_id', 'price'], unique=False)
    op.create_table('tonnel_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('auth_data', sa.Text(), nullable=True, comment='DEPRECATED - use auth_data_encrypted'),
    sa.Column('auth_data_encrypted', sa.Text(), nullable=True, comment='Encrypted auth data with Fernet'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tonnel_accounts_account_id', 'tonnel_accounts', ['account_id'], unique=False)
    op.create_index('ix_tonnel_accounts_is_active', 'tonnel_accounts', ['is_active'], unique=False)
    op.create_index('ix_tonnel_accounts_user_id', 'tonnel_accounts', ['user_id'], unique=False)
    op.create_table('trade_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_deal_gived_gifts',
    sa.Column('trade_deal_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['trade_deal_id'], ['trade_deals.id'], )
    )
    op.create_table('trade_deal_sended_gifts',
    sa.Column('trade_deal_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['trade_deal_id'], ['trade_deals.id'], )
    )
    op.create_table('trade_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=True),
    sa.Column('collection', sa.String(length=64), nullable=True),
    sa.Column('backdrop', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_bid', sa.BigInteger(), nullable=False, comment='Начальная ставка в nanotons'),
    sa.Column('step_bid', sa.Float(), nullable=False, comment='Шаг ставки в процентах'),
    sa.Column('last_bid', sa.BigInteger(), nullable=True, comment='Последняя ставка в nanotons'),
    sa.Column('expired_at', sa.DateTime(), nullable=False, comment='Время окончания аукциона'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('last_bid IS NULL OR last_bid >= start_bid', name='check_auction_last_bid_valid'),
    sa.CheckConstraint('start_bid > 0', name='check_auction_start_bid_positive'),
    sa.CheckConstraint('step_bid > 0 AND step_bid <= 100', name='check_auction_step_bid_range'),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_expired_at'), 'auctions', ['expired_at'], unique=False)
    op.create_index(op.f('ix_auctions_last_bid'), 'auctions', ['last_bid'], unique=False)
    op.create_index(op.f('ix_auctions_nft_id'), 'auctions', ['nft_id'], unique=False)
    op.create_index(op.f('ix_auctions_start_bid'), 'auctions', ['start_bid'], unique=False)
    op.create_index('ix_auctions_user_expired', 'auctions', ['user_id', 'expired_at'], unique=False)
    op.create_index(op.f('ix_auctions_user_id'), 'auctions', ['user_id'], unique=False)
    op.create_table('channels_gifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nft_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False, comment='Предложенная цена'),
    sa.Column('reciprocal_price', sa.BigInteger(), nullable=True, comment='Встречная цена'),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('price > 0', name='check_nft_offer_price_positive'),
    sa.CheckConstraint('reciprocal_price IS NULL OR reciprocal_price > 0', name='check_nft_offer_reciprocal_price_positive'),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nft_offers_nft_user', 'nft_orders', ['nft_id', 'user_id'], unique=False)
    op.create_index('ix_nft_offers_updated', 'nft_orders', ['updated'], unique=False)
    op.create_index(op.f('ix_nft_orders_nft_id'), 'nft_orders', ['nft_id'], unique=False)
    op.create_index(op.f('ix_nft_orders_price'), 'nft_orders', ['price'], unique=False)
    op.create_index(op.f('ix_nft_orders_updated'), 'nft_orders', ['updated'], unique=False)
    op.create_index(op.f('ix_nft_orders_user_id'), 'nft_orders', ['user_id'], unique=False)
    op.create_table('tonnel_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tonnel_account_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False, comment='buy, sell, listing, price_update, offer, bid'),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('asset', sa.String(length=10), server_default='TON', nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=True),
    sa.Column('gift_num', sa.Integer(), nullable=True),
    sa.Column('gift_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('backdrop', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('auction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tonnel_account_id'], ['tonnel_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tonnel_activities_activity_type', 'tonnel_activities', ['activity_type'], unique=False)
    op.create_index('ix_tonnel_activities_created_at', 'tonnel_activities', ['created_at'], unique=False)
    op.create_index('ix_tonnel_activities_gift_id', 'tonnel_activities', ['gift_id'], unique=False)
    op.create_index('ix_tonnel_activities_tonnel_account_id', 'tonnel_activities', ['tonnel_account_id'], unique=False)
    op.create_table('tonnel_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tonnel_account_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False, comment='TON, USDT, TONNEL'),
    sa.Column('balance', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('frozen_funds', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tonnel_account_id'], ['tonnel_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tonnel_balances_asset', 'tonnel_balances', ['asset'], unique=False)
    op.create_index('ix_tonnel_balances_tonnel_account_id', 'tonnel_balances', ['tonnel_account_id'], unique=False)
    op.create_table('tonnel_nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tonnel_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gift_id', sa.BigInteger(), nullable=False, comment='ID подарка в Tonnel'),
    sa.Column('gift_num', sa.Integer(), nullable=True, comment='Номер подарка в Telegram'),
    sa.Column('gift_name', sa.String(length=255), nullable=True, comment='Название подарка'),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('model_rarity', sa.Float(), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('symbol_rarity', sa.Float(), nullable=True),
    sa.Column('backdrop', sa.String(length=255), nullable=True),
    sa.Column('backdrop_rarity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('asset', sa.String(length=10), server_default='TON', nullable=False, comment='TON, USDT, TONNEL'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='listed, unlisted, sold'),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('custom_emoji_id', sa.String(length=255), nullable=True),
    sa.Column('premarket', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('telegram_marketplace', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mintable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('bundle', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tonnel_account_id'], ['tonnel_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tonnel_nfts_gift_id', 'tonnel_nfts', ['gift_id'], unique=False)
    op.create_index('ix_tonnel_nfts_price', 'tonnel_nfts', ['price'], unique=False)
    op.create_index('ix_tonnel_nfts_status', 'tonnel_nfts', ['status'], unique=False)
    op.create_index('ix_tonnel_nfts_tonnel_account_id', 'tonnel_nfts', ['tonnel_account_id'], unique=False)
    op.create_index('ix_tonnel_nfts_user_id', 'tonnel_nfts', ['user_id'], unique=False)
    op.create_table('trade_application_nfts',
    sa.Column('trade_application_id', sa.Integer(), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['trade_application_id'], ['trade_applications.id'], )
    )
    op.create_table('trade_nfts',
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], )
    )
    op.create_table('auction_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bid', sa.BigInteger(), nullable=False, comment='Размер ставки в nanotons'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('bid > 0', name='check_auction_bid_positive'),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auction_bids_auction_bid', 'auction_bids', ['auction_id', 'bid'], unique=False)
    op.create_index(op.f('ix_auction_bids_auction_id'), 'auction_bids', ['auction_id'], unique=False)
    op.create_index('ix_auction_bids_auction_user', 'auction_bids', ['auction_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_bid'), 'auction_bids', ['bid'], unique=False)
    op.create_index('ix_auction_bids_created_at', 'auction_bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_auction_bids_user_id'), 'auction_bids', ['user_id'], unique=False)
    op.create_table('deals_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['channel_deals.id'], ),
    sa.ForeignKeyConstraint(['gift_id'], ['channels_gifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tonnel_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tonnel_account_id', sa.Integer(), nullable=False),
    sa.Column('tonnel_nft_id', sa.Integer(), nullable=True),
    sa.Column('offer_type', sa.String(length=50), nullable=False, comment='gift_offer, collection_offer, auction'),
    sa.Column('gift_id', sa.BigInteger(), nullable=True, comment='ID подарка для которого оффер'),
    sa.Column('auction_id', sa.String(length=255), nullable=True, comment='ID аукциона'),
    sa.Column('gift_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('backdrop', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('asset', sa.String(length=10), server_default='TON', nullable=False),
    sa.Column('max_nfts', sa.Integer(), nullable=True),
    sa.Column('current_nfts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, comment='active, cancelled, expired, completed'),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tonnel_account_id'], ['tonnel_accounts.id'], ),
    sa.ForeignKeyConstraint(['tonnel_nft_id'], ['tonnel_nfts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tonnel_offers_gift_id', 'tonnel_offers', ['gift_id'], unique=False)
    op.create_index('ix_tonnel_offers_offer_type', 'tonnel_offers', ['offer_type'], unique=False)
    op.create_index('ix_tonnel_offers_status', 'tonnel_offers', ['status'], unique=False)
    op.create_index('ix_tonnel_offers_tonnel_account_id', 'tonnel_offers', ['tonnel_account_id'], unique=False)
    op.create_index('ix_tonnel_offers_tonnel_nft_id', 'tonnel_offers', ['tonnel_nft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tonnel_offers_tonnel_nft_id', table_name='tonnel_offers')
    op.drop_index('ix_tonnel_offers_tonnel_account_id', table_name='tonnel_offers')
    op.drop_index('ix_tonnel_offers_status', table_name='tonnel_offers')
    op.drop_index('ix_tonnel_offers_offer_type', table_name='tonnel_offers')
    op.drop_index('ix_tonnel_offers_gift_id', table_name='tonnel_offers')
    op.drop_table('tonnel_offers')
    op.drop_table('deals_gifts')
    op.drop_index(op.f('ix_auction_bids_user_id'), table_name='auction_bids')
    op.drop_index('ix_auction_bids_created_at', table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_bid'), table_name='auction_bids')
    op.drop_index('ix_auction_bids_auction_user', table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_id'), table_name='auction_bids')
    op.drop_index('ix_auction_bids_auction_bid', table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_table('trade_nfts')
    op.drop_table('trade_application_nfts')
    op.drop_index('ix_tonnel_nfts_user_id', table_name='tonnel_nfts')
    op.drop_index('ix_tonnel_nfts_tonnel_account_id', table_name='tonnel_nfts')
    op.drop_index('ix_tonnel_nfts_status', table_name='tonnel_nfts')
    op.drop_index('ix_tonnel_nfts_price', table_name='tonnel_nfts')
    op.drop_index('ix_tonnel_nfts_gift_id', table_name='tonnel_nfts')
    op.drop_table('tonnel_nfts')
    op.drop_index('ix_tonnel_balances_tonnel_account_id', table_name='tonnel_balances')
    op.drop_index('ix_tonnel_balances_asset', table_name='tonnel_balances')
    op.drop_table('tonnel_balances')
    op.drop_index('ix_tonnel_activities_tonnel_account_id', table_name='tonnel_activities')
    op.drop_index('ix_tonnel_activities_gift_id', table_name='tonnel_activities')
    op.drop_index('ix_tonnel_activities_created_at', table_name='tonnel_activities')
    op.drop_index('ix_tonnel_activities_activity_type', table_name='tonnel_activities')
    op.drop_table('tonnel_activities')
    op.drop_index(op.f('ix_nft_orders_user_id'), table_name='nft_orders')
    op.drop_index(op.f('ix_nft_orders_updated'), table_name='nft_orders')
    op.drop_index(op.f('ix_nft_orders_price'), table_name='nft_orders')
    op.drop_index(op.f('ix_nft_orders_nft_id'), table_name='nft_orders')
    op.drop_index('ix_nft_offers_updated', table_name='nft_orders')
    op.drop_index('ix_nft_offers_nft_user', table_name='nft_orders')
    op.drop_table('nft_orders')
    op.drop_table('channels_gifts')
    op.drop_index(op.f('ix_auctions_user_id'), table_name='auctions')
    op.drop_index('ix_auctions_user_expired', table_name='auctions')
    op.drop_index(op.f('ix_auctions_start_bid'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_nft_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_last_bid'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_expired_at'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_table('trade_requirements')
    op.drop_table('trade_deal_sended_gifts')
    op.drop_table('trade_deal_gived_gifts')
    op.drop_table('trade_applications')
    op.drop_index('ix_tonnel_accounts_user_id', table_name='tonnel_accounts')
    op.drop_index('ix_tonnel_accounts_is_active', table_name='tonnel_accounts')
    op.drop_index('ix_tonnel_accounts_account_id', table_name='tonnel_accounts')
    op.drop_table('tonnel_accounts')
    op.drop_index('ix_nfts_user_price', table_name='nfts')
    op.drop_index(op.f('ix_nfts_user_id'), table_name='nfts')
    op.drop_index('ix_nfts_price_not_null', table_name='nfts', postgresql_where=sa.text('price IS NOT NULL'))
    op.drop_index(op.f('ix_nfts_price'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_msg_id'), table_name='nfts')
    op.drop_index('ix_nfts_gift_price', table_name='nfts')
    op.drop_index(op.f('ix_nfts_gift_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_account_id'), table_name='nfts')
    op.drop_table('nfts')
    op.drop_table('channels')
    op.drop_table('trades')
    op.drop_table('trade_deals')
    op.drop_index(op.f('ix_nft_presales_user_id'), table_name='nft_presales')
    op.drop_index('ix_nft_presales_user_buyer', table_name='nft_presales')
    op.drop_index(op.f('ix_nft_presales_transfer_time'), table_name='nft_presales')
    op.drop_index(op.f('ix_nft_presales_price'), table_name='nft_presales')
    op.drop_index(op.f('ix_nft_presales_gift_id'), table_name='nft_presales')
    op.drop_index(op.f('ix_nft_presales_buyer_id'), table_name='nft_presales')
    op.drop_table('nft_presales')
    op.drop_index(op.f('ix_nft_deals_seller_id'), table_name='nft_deals')
    op.drop_index('ix_nft_deals_seller_buyer', table_name='nft_deals')
    op.drop_index(op.f('ix_nft_deals_price'), table_name='nft_deals')
    op.drop_index('ix_nft_deals_gift_price', table_name='nft_deals')
    op.drop_index(op.f('ix_nft_deals_gift_id'), table_name='nft_deals')
    op.drop_index('ix_nft_deals_created_at', table_name='nft_deals')
    op.drop_index(op.f('ix_nft_deals_buyer_id'), table_name='nft_deals')
    op.drop_table('nft_deals')
    op.drop_index('ix_market_nft_floors_name', table_name='market_nft_floors')
    op.drop_index('ix_market_nft_floors_market_id', table_name='market_nft_floors')
    op.drop_index('ix_market_nft_floors_created_at', table_name='market_nft_floors')
    op.drop_table('market_nft_floors')
    op.drop_table('channel_deals')
    op.drop_index(op.f('ix_balance_withdraws_user_id'), table_name='balance_withdraws')
    op.drop_index(op.f('ix_balance_withdraws_idempotency_key'), table_name='balance_withdraws')
    op.drop_table('balance_withdraws')
    op.drop_index(op.f('ix_balance_topups_user_id'), table_name='balance_topups')
    op.drop_table('balance_topups')
    op.drop_index(op.f('ix_auction_deals_seller_id'), table_name='auction_deals')
    op.drop_index('ix_auction_deals_seller_buyer', table_name='auction_deals')
    op.drop_index(op.f('ix_auction_deals_price'), table_name='auction_deals')
    op.drop_index('ix_auction_deals_gift_price', table_name='auction_deals')
    op.drop_index(op.f('ix_auction_deals_gift_id'), table_name='auction_deals')
    op.drop_index('ix_auction_deals_created_at', table_name='auction_deals')
    op.drop_index(op.f('ix_auction_deals_buyer_id'), table_name='auction_deals')
    op.drop_table('auction_deals')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index('ix_accounts_user_active', table_name='accounts')
    op.drop_index(op.f('ix_accounts_telegram_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_phone'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_premium'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index('ix_accounts_active_premium', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index('ix_users_payment_subscription', table_name='users')
    op.drop_index(op.f('ix_users_payment_status'), table_name='users')
    op.drop_index(op.f('ix_users_memo'), table_name='users')
    op.drop_index(op.f('ix_users_language'), table_name='users')
    op.drop_index('ix_users_group_payment', table_name='users')
    op.drop_index(op.f('ix_users_group'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_markets_title', table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_gifts_title_num', table_name='gifts')
    op.drop_index(op.f('ix_gifts_title'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_num'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_availability_total'), table_name='gifts')
    op.drop_index('ix_gifts_availability', table_name='gifts')
    op.drop_table('gifts')
    # ### end Alembic commands ### 